### ISSUE TITLE
Model checking course prereq

### ISSUE THREAD

**Issue by piyush-kurur** [iitpkd/courses#1]
The current assumption of the field prereq in the meta-data is that it is a list of course codes. The model checking course has a rather descriptive prereq. As a result the metadata parsing is giving a parse error and
the pdf is not generated. It is not clear how to handle this. This needs some thought.

**Comment by piyush-kurur** [comment]
One suggestion is to have two fields. prereq for the exact course pre-requsites and prereq-descriptive for a more descriptive prerequisites. The field names are up for bikeshedding. This requires some changes in
the parser but so be it.

**Comment by piyush-kurur** [comment]
May be it is better to add the verbose pre-requsites as text in the main body. That will make it simple.

**Comment by deepakrajendraprasad** [comment]
Yes, we can make it inline. I feel "Background Required" will be more clear than "Background"

**Comment by piyush-kurur** [comment]
On Thu, Aug 31, 2017 at 06:01:54AM +0000, deepakrajendraprasad wrote:
> Yes, we can make it inline. I feel "Background Required" will be more clear than "Background"

Go ahead and make that change.
